# Generated by Django 3.2 on 2021-04-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poster', models.CharField(max_length=300)),
                ('Title', models.CharField(max_length=70)),
                ('Actors', models.CharField(max_length=150)),
                ('imdbID', models.CharField(max_length=20)),
                ('Runtime', models.CharField(max_length=15)),
                ('imdbRating', models.FloatField()),
                ('Genre', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=50)),
                ('Director', models.CharField(max_length=100)),
                ('Released', models.CharField(max_length=20)),
                ('Awards', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=20)),
                ('Writer', models.CharField(max_length=300)),
                ('imdbVotes', models.CharField(max_length=15)),
                ('Country', models.CharField(max_length=20)),
                ('Box_office', models.CharField(max_length=20)),
            ],
        ),
    ]
