# Generated by Django 3.2 on 2021-04-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Language',
            field=models.CharField(max_length=100),
        ),
    ]
