# Generated by Django 3.2 on 2021-04-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_alter_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Box_office',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Released',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Type',
            field=models.CharField(max_length=50),
        ),
    ]
